Modify web page.
Jaram/Jaram.github.io pull request #2
Opened 2021-07-30 06:18 UTC by leewontae0

Modify index.html
Add css/.
Add js/.
Add img/.

2021-07-30 06:59 UTC, Taewan-P requested changes
수정 요청한 부분들 수정 부탁드리겠습니다.

2021-07-30 06:59 UTC, Taewan-P commented on css/animate.css
> +@charset "UTF-8";body{-webkit-backface-visibility:hidden}.animate{opacity:0}.animated{-webkit-animation-duration:1s;-moz-animation-duration:1s;-o-animation-duration:1s;animation-duration:1s;-webkit-a
해당 CSS 파일은 외부 라이브러리인것 같은데 CDN링크로 대체해주세요.

2021-07-30 06:59 UTC, Taewan-P commented on css/bootstrap.min.css
> +/*!
부트스트랩도 마찬가지입니다. 혹시 해당 부트스트랩 CDN이 따로 없다면 알려주세요.

2021-07-30 06:59 UTC, Taewan-P commented on css/flex-slider.css
> + * http://www.gnu.org/licenses/gpl-2.0.html
외부 라이브러리 CDN 이동 1

2021-07-30 06:59 UTC, Taewan-P commented on css/font-awesome.css
> +/*!
외부 라이브러리 CDN 이동 2

2021-07-30 06:59 UTC, Taewan-P commented on css/fullpage.min.css
> + * @license GPLv3 for open source use only
외부 라이브러리 CDN 이동 3

2021-07-30 06:59 UTC, Taewan-P commented on css/owl.carousel.css
> + * Licensed under: SEE LICENSE IN https://github.com/OwlCarousel2/OwlCarousel2/blob/master/LICENSE
외부 라이브러리 CDN 이동 4

2021-07-30 06:59 UTC, Taewan-P commented on js/bootstrap.min.js
> + * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
외부 라이브러리 CDN 이동 5

2021-07-30 06:59 UTC, Taewan-P commented on js/form.js
> +$(function() {
해당 폼은 하단에 이름과 이메일과 입력메시지를 입력하면 작동하게끔 설계되어 있던데, 어디로 전송되는건지랑 자세한 사용법 설명 부탁드립니다.

2021-07-30 06:59 UTC, Taewan-P commented on js/fullpage.min.js
> + * @license GPLv3 for open source use only
외부 라이브러리 CDN 이동 6

2021-07-30 06:59 UTC, Taewan-P commented on js/jquery.inview.min.js
> +!function(a){"function"==typeof define&&define.amd?define(["jquery"],a):"object"==typeof exports?module.exports=a(require("jquery")):a(jQuery)}(function(a){function i(){var b,c,d={height:f.innerHeigh
외부 라이브러리 CDN 이동 7

2021-07-30 06:59 UTC, Taewan-P commented on js/jquery.js
> +/*!jQuery v3.0.0 | (c) jQuery Foundation | jquery.org/license*/!function(a,b){"object"==typeof module&&"object"==typeof module.exports?module.exports=a.document?b(a,!0):function(a){if(!a.document)thr
외부 라이브러리 CDN 이동 8

2021-07-30 06:59 UTC, Taewan-P commented on js/owl.carousel.min.js
> + * Licensed under: SEE LICENSE IN https://github.com/OwlCarousel2/OwlCarousel2/blob/master/LICENSE
외부 라이브러리 CDN 이동 9

2021-07-30 06:59 UTC, Taewan-P commented on js/scrolloverflow.js
> +/*!iScroll v5.2.0 ~ (c) 2008-2016 Matteo Spinelli ~ http://cubiq.org/license*/(function(window,document,Math){var rAF=window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozReque
외부 라이브러리 CDN 이동 10

2021-07-30 06:59 UTC, Taewan-P commented on index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
메타 태그가 들어가 있는데 제대로 채워 주세요.

2021-07-30 06:59 UTC, Taewan-P commented on index.html
> +                                                        <i class="fa fa-support counter-icon" aria-hidden="true"></i><span class="count-number">99</span> Team Members
팀 멤버수가 99명으로 되어있으나 이는 항상 고정이 아니기에 부적절해 보입니다. 제가 제시하는 솔루션은:
- 무한대 
- 또는 계속 증가중임을 나타낼수 있는 어떠한 것
- 해당 부분을 삭제
가 되겠습니다.

2021-07-30 06:59 UTC, Taewan-P commented on index.html
> +                                            <span class="service-icon"><i class="fa" aria-hidden="true"><div style="width: 55px; margin-top: 10px;"><img src="./img/party.png" alt=""></div></i></span>
해당 이미지를 svg로 바꿔주시거나 hover시 색상 반전 코드를 넣어주면 감사하겠습니다.
hover 상태일때 배경화면이 흰색인데 이미지도 흰색이라 아이콘이 전혀 보이지 않는 상황입니다. 
![image](https://user-images.githubusercontent.com/27392567/127612520-39927086-e600-4c94-9773-fe6d48bc7c34.png)

2021-07-30 06:59 UTC, Taewan-P commented on index.html
> +                                            <h3>e-sports</h3>
E-sports 아이콘도 마찬가지입니다.
![image](https://user-images.githubusercontent.com/27392567/127612575-6d7cd274-0736-4485-bf78-8ad5ad47d886.png)

2021-07-30 06:59 UTC, Taewan-P commented on index.html
> +                                            <span class="service-icon"><i class="fa" aria-hidden="true"><div style="width: 55px; margin-top: 10px;"><img src="./img/study.png" alt=""></div></i></span>
![image](https://user-images.githubusercontent.com/27392567/127612665-5356a08d-f758-4ee9-824d-91b1eff6123c.png)

2021-07-30 06:59 UTC, Taewan-P commented on index.html
> +                                        <div class="service-box">
![image](https://user-images.githubusercontent.com/27392567/127612716-34e4d7c1-748e-4b93-a958-b5f49d3897b8.png)
HYBUS 항목만 다른 항목과 margin 차이가 납니다. 해당 부분 수정이 필요합니다.

2021-07-30 06:59 UTC, Taewan-P commented on index.html
> +                                        <div class="service-box">
근데 해당 부분에서 다들 "학회 활동"에 대한 부분을 설명하지만 HYBUS만은 카테고리가 다르니 차라리 빼고 다른걸 넣거나 하는게 좋을 것 같습니다.

2021-07-30 06:59 UTC, Taewan-P commented on index.html
> +                                            <div class="input-field">
해당 부분 desktop mode에서 상단 정렬이 되어있지 않는 상태입니다.
![image](https://user-images.githubusercontent.com/27392567/127613031-9cbc97b8-e72c-409d-8be8-94232b8aa270.png)

2021-07-30 06:59 UTC, Taewan-P commented on index.html
> +                                            <div class="input-field">
또한 UI 적으로 input field 왼쪽에 있는 상자들의 height가 더 두꺼운 상태인데 이는 통일성이 없어 보입니다.

2021-07-30 06:59 UTC, Taewan-P commented on index.html
> +                                            <div class="input-field">
추가적으로 리뷰를 하나 달았지만 Name, E-mail, Message를 어디다 submit 하는지 알려주시면 감사하겠습니다.

2021-07-30 06:59 UTC, Taewan-P commented on index.html
> +        <div id="social-icons">
해당 아이콘들이 가지는 의미가 궁금합니다.
Contact Us라는 section이 이미 있기 때문에 기능 중복이라고 생각됩니다.

2021-07-30 06:59 UTC, Taewan-P commented on index.html
> +                    <li><a href="mailto:swimingtw@gmail.com" onclick="copy()" title="email"><img src="./img/email.png" width="16px"></a></li>
그리고 저번에 알려드린건데 여기 제 이메일을 올리시면 안됩니다... Jaram 이메일로 수정부탁드립니다.

2021-07-30 06:59 UTC, Taewan-P commented on index.html
> +    <script src="js/jquery.js"></script>
외부 라이브러리 스크립트가 다 CDN으로 이전 시 html에서도 수정 바랍니다.

2021-07-30 06:59 UTC, Taewan-P commented on index.html
> +                        <div class="scroll-down next-section animate" data-animate="fadeInUp"><img src="./img/mouse-scroll.png" alt=""><span>Scroll Down</span></div>
![image](https://user-images.githubusercontent.com/27392567/127613546-6f4c4817-ebfb-4aee-84cf-399c7ce4029a.png)
Mouse scroll 부분이 모바일에서 가운데 정렬이 되어있지 않습니다.

2021-07-30 06:59 UTC, Taewan-P commented on index.html
>  <html lang="en">
html 기본 언어 수정 바랍니다.

2021-07-30 07:07 UTC, Taewan-P commented
그리고 지금 커밋 내역을 보시면 
![image](https://user-images.githubusercontent.com/27392567/127614480-fefd4f88-49f6-4676-be49-b0c229ffa283.png)
프로필 사진이 제대로 나오지 않음을 확인할 수 있는데 이는 로컬 git 환경에서 user.name과 user.email 이 정상적으로 등록되지 않았음을 의미합니다.
다음에 커밋하시기 전에 꼭 git config에서 user.name과 user.email을 등록해주세요 :)

2021-08-11 09:10 UTC, leewontae0 commented on css/animate.css
> +@charset "UTF-8";body{-webkit-backface-visibility:hidden}.animate{opacity:0}.animated{-webkit-animation-duration:1s;-moz-animation-duration:1s;-o-animation-duration:1s;animation-duration:1s;-webkit-a
"https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.css"
위 해당 링크로 cdn 처리했는데, 적용이 되지 않아서 원상태로 놔뒀습니다.

2021-08-11 09:11 UTC, leewontae0 commented on js/jquery.js
> +/*!jQuery v3.0.0 | (c) jQuery Foundation | jquery.org/license*/!function(a,b){"object"==typeof module&&"object"==typeof module.exports?module.exports=a.document?b(a,!0):function(a){if(!a.document)thr
https://cdnjs.cloudflare.com/ajax/libs/jquery.inview/1.0.0/jquery.inview.min.js
마찬가지로 동일한 현상이 일어나서, 원상태로 놔뒀습니다.

2021-08-11 09:15 UTC, Taewan-P commented on css/animate.css
> +@charset "UTF-8";body{-webkit-backface-visibility:hidden}.animate{opacity:0}.animated{-webkit-animation-duration:1s;-moz-animation-duration:1s;-o-animation-duration:1s;animation-duration:1s;-webkit-a
둘이 똑같은 파일인지 확인했나요?
css/animate.css 첫줄에 `-webkit-backface-visibility` 만 확인해도 완전 다른 CSS 파일인 것 같은데..

2021-08-11 09:18 UTC, Taewan-P commented on js/jquery.js
> +/*!jQuery v3.0.0 | (c) jQuery Foundation | jquery.org/license*/!function(a,b){"object"==typeof module&&"object"==typeof module.exports?module.exports=a.document?b(a,!0):function(a){if(!a.document)thr
여기도 마찬가지입니다.
그리고 링크를 잘못 걸었는지는 모르겠으나 jquery파일에 jquery.inview.min 링크를 다셨습니다.

2021-08-11 09:57 UTC, leewontae0 commented on css/animate.css
> +@charset "UTF-8";body{-webkit-backface-visibility:hidden}.animate{opacity:0}.animated{-webkit-animation-duration:1s;-moz-animation-duration:1s;-o-animation-duration:1s;animation-duration:1s;-webkit-a
앞서 말씀 드린 건 동일한 파일을 못 찾았다는 의도였습니다.
공식홈페이지(https://animate.style/)에서도 cdn 적용 시 cdnjs 를 통하는 링크를 사용하고 있는데, cdnjs 에서 animate.css 파일을 대략 찾아봤을 땐 동일한 파일은 없어 보였습니다.

2021-08-11 09:58 UTC, leewontae0 commented on js/jquery.js
> +/*!jQuery v3.0.0 | (c) jQuery Foundation | jquery.org/license*/!function(a,b){"object"==typeof module&&"object"==typeof module.exports?module.exports=a.document?b(a,!0):function(a){if(!a.document)thr
아 이 comment는 위 jquery.inview.min.js 에 달았어야했는데, 죄송합니다.

2021-08-11 10:00 UTC, Taewan-P commented on css/animate.css
> +@charset "UTF-8";body{-webkit-backface-visibility:hidden}.animate{opacity:0}.animated{-webkit-animation-duration:1s;-moz-animation-duration:1s;-o-animation-duration:1s;animation-duration:1s;-webkit-a
저 animate.css 파일을 어디서 받으셨나요?
공식 홈페이지에는 css 다운로드 받는페이지가 없는걸로 보아, CDN링크 타고 받았을텐데, 해당 링크를 넣으면 되는거 아닌가요?
CSS의 정확한 출처가 필요합니다.

2021-08-11 10:08 UTC, leewontae0 commented on css/animate.css
> +@charset "UTF-8";body{-webkit-backface-visibility:hidden}.animate{opacity:0}.animated{-webkit-animation-duration:1s;-moz-animation-duration:1s;-o-animation-duration:1s;animation-duration:1s;-webkit-a
https://themewagon.com/themes/free-modern-bootstrap-4-html5-portfolio-website-template-elegence/
해당 링크를 통해서 테마를 다운받았습니다.

2021-08-11 10:12 UTC, Taewan-P commented on css/animate.css
> +@charset "UTF-8";body{-webkit-backface-visibility:hidden}.animate{opacity:0}.animated{-webkit-animation-duration:1s;-moz-animation-duration:1s;-o-animation-duration:1s;animation-duration:1s;-webkit-a
이건 위에 언급된 [공식홈페이지](https://animate.style) 에서 따온 animate.css가 아닙니다. 만든 사람이 따로 생성한 css 파일으로 보입니다.

2021-08-11 10:13 UTC, Taewan-P commented on css/animate.css
> +@charset "UTF-8";body{-webkit-backface-visibility:hidden}.animate{opacity:0}.animated{-webkit-animation-duration:1s;-moz-animation-duration:1s;-o-animation-duration:1s;animation-duration:1s;-webkit-a
해당 건은 resolve 처리하겠습니다

2021-08-11 10:16 UTC, Taewan-P commented on js/jquery.inview.min.js
> +!function(a){"function"==typeof define&&define.amd?define(["jquery"],a):"object"==typeof exports?module.exports=a(require("jquery")):a(jQuery)}(function(a){function i(){var b,c,d={height:f.innerHeigh
해당라이브러리 [출처](https://github.com/protonet/jquery.inview)

2021-08-11 10:27 UTC, Taewan-P commented
@leewontae0 위에서 반영안된 부분 외에 반영한 부분 커밋후 멘션 바랍니다

2021-08-11 14:36 UTC, Taewan-P approved these changes
LGTM

2021-08-11 14:37 UTC, merged